feat(table): update table to support error messages
eclipse-tractusx/portal-shared-components pull request #230
Opened 2024-07-12 07:23 UTC by lavanya-bmw

## Description

Updated table component to support error messages

## Why

to enhance table component to support error messages

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/891
https://github.com/eclipse-tractusx/portal-frontend/issues/888

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2024-07-12 11:42 UTC, lavanya-bmw commented on src/components/basic/Table/index.tsx
> +    } else if (error != null) {
Removed Unneeded defensive code

2024-07-12 12:12 UTC, oyo requested changes
unnecessary else

2024-07-12 12:12 UTC, oyo commented on src/components/basic/Table/index.tsx
> +    } else {
we don't need else if the previous if returns 100% sure. Change from

```diff
- if (something) {
-   return x
- } else {
-   doMore()
- }
``` 

to

```diff
+ if (something) {
+   return x
+ }
+ doMore()
```

2024-07-12 12:12 UTC, oyo commented on src/components/basic/Table/index.tsx
> +      } else {
again no else needed

2024-07-15 10:43 UTC, oyo approved these changes

2024-07-15 10:44 UTC, merged