fix: updated deprecated type usage
eclipse-tractusx/portal-shared-components pull request #306
Opened 2024-09-10 12:04 UTC by charmi-v

## Description

Code Cleanup: Updated deprecated type usage

## Why

After migrating to v8, there are still instances of a deprecated type that has been removed. A replacement type is available.

## Issue

#305 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

2024-09-13 11:44 UTC, manojava-gk commented
Run `yarn pretty` manually and then push the changes to fix `pr checks` issue

2024-09-13 12:03 UTC, oyo requested changes
Kindly resolve conflicts occurring due to PR #309 enforcing import order

2024-09-13 12:12 UTC, charmi-v commented
> Kindly resolve conflicts occurring due to PR #309 enforcing import order

Conflicts are resolved now

2024-09-16 12:30 UTC, oyo approved these changes

2024-09-16 12:30 UTC, merged