fix(card): status fix
eclipse-tractusx/portal-shared-components pull request #42
Opened 2023-09-01 07:31 UTC by lavanya-bmw

## Description

 Converted status condition to lowercase

## Why

To include active apps from service overview for sub-menu

## Issue

Ref: CPLP-3181

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-09-08 12:43 UTC, evegufy requested changes
Looks good. Could you please also update changelog?

2023-09-11 08:44 UTC, oyo submitted a review, later dismissed

2023-09-11 08:49 UTC, evegufy submitted a review, later dismissed

2023-09-11 08:59 UTC, oyo approved these changes

2023-09-11 09:00 UTC, merged