feat(linter): add type for imports
eclipse-tractusx/portal-shared-components pull request #59
Opened 2023-09-22 11:19 UTC by nidhigarg-bmw

## Description

add types for imports

## Why

To remove lint errors

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-09-25 12:42 UTC, oyo submitted a review, later dismissed

2023-09-25 12:42 UTC, oyo approved these changes

2023-09-25 12:45 UTC, oyo requested changes
looks good - but after fixing the rule should also be activated by removing this line in `.eslintrc.json`
https://github.com/eclipse-tractusx/portal-shared-components/blob/main/.eslintrc.json#L35

please run `yarn lint` before pushing to make sure the issues are resolved

2023-09-26 06:39 UTC, nidhigarg-bmw commented
> looks good - but after fixing the rule should also be activated by removing this line in `.eslintrc.json` https://github.com/eclipse-tractusx/portal-shared-components/blob/main/.eslintrc.json#L35
> 
> please run `yarn lint` before pushing to make sure the issues are resolved

@oyo Made the changes

2023-09-26 10:49 UTC, oyo approved these changes

2023-09-26 10:49 UTC, merged