fix(order status button): ui changes
eclipse-tractusx/portal-shared-components pull request #79
Opened 2023-12-15 06:23 UTC by nidhigarg-bmw

## Description

Order Status Button: Make textual ui changes to look more good
Card: Make status bar text in lowercase

## Why

UI Improvements

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-12-26 05:15 UTC, lavanya-bmw requested changes

2023-12-26 05:15 UTC, lavanya-bmw commented on CHANGELOG.md
> +
Please add this log in 2.1.12

2023-12-26 05:27 UTC, lavanya-bmw approved these changes
lgtm

2024-01-08 03:46 UTC, oyo approved these changes

2024-01-08 03:46 UTC, merged